trigger:
  - master
  
resources:
  - repo: self
  
variables:
  spnId: '9ccb96ba-b510-4109-b821-8427f5109971'
  # spnPassword must be a secret defined on the pipeline in AzDO
  # use this to create the SPN: az ad sp create-for-rbac --skip-assignment --name cdTailWindSPN
  # make a note of the client key
  resourceGroup: 'cd-tailwind'
  azureSub: '10m Client Demo'
  deployfrom: 'Deploy'

jobs:
- job: deploy_infra
  displayName: Deploy Infrastructure
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureSub)
      scriptType: pscore
      scriptPath: Deploy/Deploy-Unified-Pipeline.ps1
      scriptArguments:
        -resourceGroup $(resourceGroup) `
        -location westus2 `
        -clientId $(spnId) `
        -password $(spnPassword)
      azurePowerShellVersion: latestVersion
      powerShellErrorActionPreference: continue
      workingDirectory: $(Build.SourcesDirectory)/Deploy