apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.certName }}
  namespace: default
spec:
  secretName: {{ .Values.certSecretName }}
  dnsNames:
  - {{ .Values.domain }}
  issuerRef:
    name: {{ .Values.issuerName }}
    kind: Issuer
    group: cert-manager.io